// flow-typed signature: 2ffb0e43fbb72fb75225ddf3e5deeae2
// flow-typed version: <<STUB>>/baconjs_v^0.7.95/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'baconjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'baconjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'baconjs/assemble-specs' {
  declare module.exports: any;
}

declare module 'baconjs/assemble' {
  declare module.exports: any;
}

declare module 'baconjs/build-deps' {
  declare module.exports: any;
}

declare module 'baconjs/dist/Bacon' {
  declare module.exports: any;
}

declare module 'baconjs/dist/Bacon.min' {
  declare module.exports: any;
}

declare module 'baconjs/dist/Bacon.noAssert' {
  declare module.exports: any;
}

declare module 'baconjs/test-individually' {
  declare module.exports: any;
}

// Filename aliases
declare module 'baconjs/assemble-specs.js' {
  declare module.exports: $Exports<'baconjs/assemble-specs'>;
}
declare module 'baconjs/assemble.js' {
  declare module.exports: $Exports<'baconjs/assemble'>;
}
declare module 'baconjs/build-deps.js' {
  declare module.exports: $Exports<'baconjs/build-deps'>;
}
declare module 'baconjs/dist/Bacon.js' {
  declare module.exports: $Exports<'baconjs/dist/Bacon'>;
}
declare module 'baconjs/dist/Bacon.min.js' {
  declare module.exports: $Exports<'baconjs/dist/Bacon.min'>;
}
declare module 'baconjs/dist/Bacon.noAssert.js' {
  declare module.exports: $Exports<'baconjs/dist/Bacon.noAssert'>;
}
declare module 'baconjs/test-individually.js' {
  declare module.exports: $Exports<'baconjs/test-individually'>;
}
