// flow-typed signature: 6f743a9d44ed83c6cd53d89a17b0c035
// flow-typed version: <<STUB>>/expect.js_v^0.3.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expect.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'expect.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'expect.js/index' {
  declare module.exports: $Exports<'expect.js'>;
}
declare module 'expect.js/index.js' {
  declare module.exports: $Exports<'expect.js'>;
}
